// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using studentMangementSystem.Data;

#nullable disable

namespace studentMangementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260116032710_addedhash")]
    partial class addedhash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("DeliveryOrder")
                .StartsAt(1000L);

            modelBuilder.Entity("studentMangementSystem.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeliveryOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR DeliveryOrder");

                    b.Property<string>("DepartmentHead")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliveryOrder = 0,
                            DepartmentHead = "Oliver Herston",
                            Name = "Mechanical Engineering"
                        },
                        new
                        {
                            Id = 2,
                            DeliveryOrder = 0,
                            DepartmentHead = "Mike Hary",
                            Name = "Electrical Engineering"
                        },
                        new
                        {
                            Id = 3,
                            DeliveryOrder = 0,
                            DepartmentHead = "Steven Odegard",
                            Name = "Civil Engineering "
                        },
                        new
                        {
                            Id = 4,
                            DeliveryOrder = 0,
                            DepartmentHead = "Jordon Harmi",
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 5,
                            DeliveryOrder = 0,
                            DepartmentHead = "Alina Foc",
                            Name = "Management Information Systems"
                        },
                        new
                        {
                            Id = 6,
                            DeliveryOrder = 0,
                            DepartmentHead = "Zendaia ",
                            Name = "Information technology"
                        },
                        new
                        {
                            Id = 7,
                            DeliveryOrder = 0,
                            DepartmentHead = "Sedeny Foler",
                            Name = "business management"
                        },
                        new
                        {
                            Id = 8,
                            DeliveryOrder = 0,
                            DepartmentHead = "Hary Tormy",
                            Name = "Fine Arts"
                        },
                        new
                        {
                            Id = 9,
                            DeliveryOrder = 0,
                            DepartmentHead = "Tom Armorstrong",
                            Name = "Law"
                        },
                        new
                        {
                            Id = 10,
                            DeliveryOrder = 0,
                            DepartmentHead = "Keny Ackremany",
                            Name = "Primary Education"
                        });
                });

            modelBuilder.Entity("studentMangementSystem.Models.DepartmentStudyYear", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("StudyYearId")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId", "StudyYearId");

                    b.HasIndex("StudyYearId");

                    b.ToTable("DepartmentStudyYears");
                });

            modelBuilder.Entity("studentMangementSystem.Models.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("studentMangementSystem.Models.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Coach")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("DeliveryOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR DeliveryOrder");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Sport");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Coach = "John Doe",
                            DeliveryOrder = 0,
                            Name = "Football"
                        },
                        new
                        {
                            Id = 2,
                            Coach = "Jane Smith",
                            DeliveryOrder = 0,
                            Name = "Basketball"
                        },
                        new
                        {
                            Id = 3,
                            Coach = "Mike Johnson",
                            DeliveryOrder = 0,
                            Name = "Tennis"
                        });
                });

            modelBuilder.Entity("studentMangementSystem.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Successful"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Failed"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Graduated"
                        });
                });

            modelBuilder.Entity("studentMangementSystem.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DeliveryOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR DeliveryOrder");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("InrollDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("StudyYearId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SportId");

                    b.HasIndex("StatusId");

                    b.HasIndex("StudyYearId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("studentMangementSystem.Models.StudentSubject", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("StudentDtoId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalMarks")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("StudentId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentSubjects");
                });

            modelBuilder.Entity("studentMangementSystem.Models.StudyYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("StudyYears");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Preparatory Engineering"
                        },
                        new
                        {
                            Id = 2,
                            Name = "First Year"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Second Year"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Third Year"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fourth Year"
                        });
                });

            modelBuilder.Entity("studentMangementSystem.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreditHours")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR DeliveryOrder");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("StudyYearId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectDoctor")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("StudyYearId");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("studentMangementSystem.Models.DepartmentStudyYear", b =>
                {
                    b.HasOne("studentMangementSystem.Models.Department", "Department")
                        .WithMany("DepartmentStudyYears")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("studentMangementSystem.Models.StudyYear", "StudyYear")
                        .WithMany("DepartmentStudyYears")
                        .HasForeignKey("StudyYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("StudyYear");
                });

            modelBuilder.Entity("studentMangementSystem.Models.Student", b =>
                {
                    b.HasOne("studentMangementSystem.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("studentMangementSystem.Models.Sport", "Sport")
                        .WithMany("Students")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("studentMangementSystem.Models.Status", "Status")
                        .WithMany("Students")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("studentMangementSystem.Models.StudyYear", "StudyYear")
                        .WithMany("Students")
                        .HasForeignKey("StudyYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Sport");

                    b.Navigation("Status");

                    b.Navigation("StudyYear");
                });

            modelBuilder.Entity("studentMangementSystem.Models.StudentSubject", b =>
                {
                    b.HasOne("studentMangementSystem.Models.Student", "Student")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("studentMangementSystem.Models.Subject", "Subject")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("studentMangementSystem.Models.Subject", b =>
                {
                    b.HasOne("studentMangementSystem.Models.Department", "Department")
                        .WithMany("Subjects")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("studentMangementSystem.Models.StudyYear", "StudyYear")
                        .WithMany("Subjects")
                        .HasForeignKey("StudyYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("StudyYear");
                });

            modelBuilder.Entity("studentMangementSystem.Models.Department", b =>
                {
                    b.Navigation("DepartmentStudyYears");

                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("studentMangementSystem.Models.Sport", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("studentMangementSystem.Models.Status", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("studentMangementSystem.Models.Student", b =>
                {
                    b.Navigation("StudentSubjects");
                });

            modelBuilder.Entity("studentMangementSystem.Models.StudyYear", b =>
                {
                    b.Navigation("DepartmentStudyYears");

                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("studentMangementSystem.Models.Subject", b =>
                {
                    b.Navigation("StudentSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
